import { computed } from 'vue'
import { useAppStore } from './stores/app'

export type Language = 'zh-CN' | 'en' | 'de'
const messages: Record<Language, Record<string, string>> = {
  'zh-CN': {
    brand: '云相册', welcome: '欢迎回来', loginHint: '登录后即可查看云端相机上传的照片', email: '邮箱', password: '密码', login: '登录', register: '注册账号', forgot: '忘记密码？', loading: '加载中…', logout: '退出登录', album: '相册', mine: '我的', select: '选择', cancel: '取消', delete: '删除', language: '语言设置', today: '今天', sevenDays: '最近 7 天', month: '最近 1 个月', all: '全部', noDevice: '尚未绑定设备', noDeviceHint: '绑定相机设备后，设备上传的照片会显示在这里。', bind: '立即绑定设备', noPhotos: '云端还没有照片', noPhotosHint: '设备上传并完成云端处理后，照片会显示在这里。', selected: '已选 {n} / 9', deleteConfirm: '确定删除选中的照片吗？删除后无法恢复。', deleteSuccess: '照片已删除', loginError: '邮箱或密码错误', emailError: '请输入正确的邮箱地址', passwordError: '密码至少 6 位', flowRegister: '创建账号', flowReset: '重置密码', next: '下一步', sendCode: '发送验证码', code: '验证码', codeHint: '请输入邮箱收到的验证码', newPassword: '新密码', confirmPassword: '确认密码', done: '完成', codeSent: '验证码已发送', operationError: '操作失败，请稍后重试', resetSuccess: '密码已重置，请登录', registerSuccess: '注册成功，请登录', backLogin: '返回登录', languageSaved: '语言已更新', languageSyncError: '语言同步失败，请稍后重试', storage: '云端存储空间', device: '我的设备', plans: '容量购买', entitlements: '存储权益', noEntitlement: '尚未绑定设备', loggedOut: '已退出登录'
  },
  en: {
    brand: 'Cloud Album', welcome: 'Welcome back', loginHint: 'View photos uploaded by your camera after signing in', email: 'Email', password: 'Password', login: 'Sign in', register: 'Create account', forgot: 'Forgot password?', loading: 'Loading…', logout: 'Sign out', album: 'Album', mine: 'Me', select: 'Select', cancel: 'Cancel', delete: 'Delete', language: 'Language', today: 'Today', sevenDays: 'Last 7 days', month: 'Last month', all: 'All', noDevice: 'No device bound', noDeviceHint: 'Bind a camera to see its uploaded photos here.', bind: 'Bind a device', noPhotos: 'No photos yet', noPhotosHint: 'Photos will appear after your device uploads and processing completes.', selected: 'Selected {n} / 9', deleteConfirm: 'Delete the selected photos? This cannot be undone.', deleteSuccess: 'Photos deleted', loginError: 'Incorrect email or password', emailError: 'Enter a valid email address', passwordError: 'Password must be at least 6 characters', flowRegister: 'Create account', flowReset: 'Reset password', next: 'Next', sendCode: 'Send code', code: 'Verification code', codeHint: 'Enter the code sent to your email', newPassword: 'New password', confirmPassword: 'Confirm password', done: 'Done', codeSent: 'Code sent', operationError: 'Operation failed. Try again.', resetSuccess: 'Password reset. Please sign in.', registerSuccess: 'Account created. Please sign in.', backLogin: 'Back to sign in', languageSaved: 'Language updated', languageSyncError: 'Could not sync language', storage: 'Cloud storage', device: 'My device', plans: 'Buy storage', entitlements: 'Storage benefits', noEntitlement: 'No device bound', loggedOut: 'Signed out'
  },
  de: {
    brand: 'Cloud-Album', welcome: 'Willkommen zurück', loginHint: 'Nach der Anmeldung sehen Sie die Kamera-Uploads', email: 'E-Mail', password: 'Passwort', login: 'Anmelden', register: 'Konto erstellen', forgot: 'Passwort vergessen?', loading: 'Laden…', logout: 'Abmelden', album: 'Album', mine: 'Ich', select: 'Auswählen', cancel: 'Abbrechen', delete: 'Löschen', language: 'Sprache', today: 'Heute', sevenDays: 'Letzte 7 Tage', month: 'Letzter Monat', all: 'Alle', noDevice: 'Kein Gerät verbunden', noDeviceHint: 'Verbinden Sie eine Kamera, um Uploads zu sehen.', bind: 'Gerät verbinden', noPhotos: 'Noch keine Fotos', noPhotosHint: 'Fotos erscheinen nach Upload und Verarbeitung.', selected: 'Ausgewählt {n} / 9', deleteConfirm: 'Ausgewählte Fotos löschen? Dies kann nicht rückgängig gemacht werden.', deleteSuccess: 'Fotos gelöscht', loginError: 'E-Mail oder Passwort falsch', emailError: 'Gültige E-Mail eingeben', passwordError: 'Passwort mindestens 6 Zeichen', flowRegister: 'Konto erstellen', flowReset: 'Passwort zurücksetzen', next: 'Weiter', sendCode: 'Code senden', code: 'Bestätigungscode', codeHint: 'Code aus der E-Mail eingeben', newPassword: 'Neues Passwort', confirmPassword: 'Passwort bestätigen', done: 'Fertig', codeSent: 'Code gesendet', operationError: 'Vorgang fehlgeschlagen', resetSuccess: 'Passwort zurückgesetzt. Bitte anmelden.', registerSuccess: 'Konto erstellt. Bitte anmelden.', backLogin: 'Zur Anmeldung', languageSaved: 'Sprache aktualisiert', languageSyncError: 'Sprache konnte nicht synchronisiert werden', storage: 'Cloud-Speicher', device: 'Mein Gerät', plans: 'Speicher kaufen', entitlements: 'Speicherrechte', noEntitlement: 'Kein Gerät verbunden', loggedOut: 'Abgemeldet'
  }
}
export function useI18n() {
  const store = useAppStore()
  const locale = computed(() => (messages[store.language as Language] ? store.language as Language : 'en'))
  const t = (key: string, vars: Record<string, string | number> = {}) => Object.entries(vars).reduce((s, [k, v]) => s.replace(`{${k}}`, String(v)), messages[locale.value][key] || key)
  return { t, locale }
}
